- hosts: localhost
  connection: local
  vars:
    vagrant_plugins_plugins:
      - sahara
      - vagrant-omnibus
    vagrant_plugins_plugins_with_version:
      - { name: vagrant-digitalocean, version: 0.6.0 }
  tasks:
    - include: 'tasks/main.yml'
